FROM debian:buster
RUN apt-get update && apt-get install vsftpd -y
COPY ./tools/vsftpd.conf /etc/vsftpd.conf
ADD ./tools/entrypoint.sh /var/run/entrypoint.sh
RUN chmod +x /var/run/entrypoint.sh
ENTRYPOINT [ "/var/run/entrypoint.sh" ]
CMD [ "/usr/sbin/vsftpd" ]

