FROM debian:buster

RUN apt-get update && apt-get install -y apache2  php php-curl libapache2-mod-php php-cli php-mysql php-gd php-fpm 

ADD ./tools/entrypoint.sh /tmp/
RUN chmod +x /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]
CMD ["service apache2 restart"]
