FROM debian:buster

RUN apt-get update && apt-get install -y php php-mysql adminer wget
RUN mkdir -p /var/www/adminer
WORKDIR /var/www/adminer
RUN wget "https://www.adminer.org/latest.php" && mv latest.php adminer.php
CMD ["php","-S","0.0.0.0:8000","-t","/var/www/adminer"]
