FROM debian:buster
RUN apt-get update && apt-get install wget -y
WORKDIR /usr/bin
RUN wget https://github.com/google/cadvisor/releases/download/v0.47.0/cadvisor-v0.47.0-linux-amd64 
RUN mv cadvisor-v0.47.0-linux-amd64 cadvisor
RUN chmod +x /usr/bin/cadvisor
ENTRYPOINT ["/usr/bin/cadvisor"]
